backend:
  name: git-gateway
  branch: main

media_folder: "/public/img/blog"
public_folder: "/img/blog"
publish_mode: editorial_workflow
logo_url: https://everwashpartners.com/img/EverWash_Logo_Blue.png
collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{slug}}
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "select", options: ["Harriet Ayoade", "Max Pulcini", "Nash Goudie", "Matthew Dimbat", "Yamilette Roman", "Ryan Caldwell", "Mike Christie", "Rachel Fry", "EverWash Newsroom"]}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["post", "blog"]}
      - {label: "Feature Image", name: "image", widget: "image", required: false}
      - {label: "Image Caption", name: "imageAlt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
 
      
      
